"""Write the seed as the dashboard's offline mock: frontend/mock/snapshot.json (+ .js for file://).

Run after changing backend/app/seed.py:  .venv/bin/python scripts/export_mock.py
The .js copy exists because browsers block fetch() of local files, but a <script> tag still loads.
"""
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from backend.app.messages import snapshot  # noqa: E402
from backend.app.repo import InMemoryRepo  # noqa: E402

out = os.path.join(os.path.dirname(__file__), "..", "frontend", "mock")
data = snapshot(InMemoryRepo())["data"]
text = json.dumps(data, indent=1)
with open(os.path.join(out, "snapshot.json"), "w") as f:
    f.write(text + "\n")
with open(os.path.join(out, "snapshot.js"), "w") as f:
    f.write("// Generated by scripts/export_mock.py from backend/app/seed.py. Do not edit by hand.\n")
    f.write("window.MOCK_SNAPSHOT = " + text + ";\n")
print("wrote frontend/mock/snapshot.json and snapshot.js")
